name: Build and deploy Node.js app to Azure Web App - sts-mesa-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Prepare for deployment
        run: |
          mkdir -p deployment
          cp -r dist package.json package-lock.json deployment/
          [ -f .env.production ] && cp .env.production deployment/ || true
          cd deployment && zip -r ../release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d deployment

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DE6A0EA8FEA147F5B676E6346C341933 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32371F979C95479F92B171C9BDA8AEE5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4529181DCB2C4DECA901A16F5A6C3B89 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sts-mesa-server'
          slot-name: 'Production'
          package: deployment
          runtime-stack: 'NODE|22-lts'
          app-settings: |
            [
              {"name": "WEBSITES_PORT", "value": "8080"},
              {"name": "NODE_ENV", "value": "production"},
              {"name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "false"}
            ]